# testing: ppc64le
language: node_js
os:
  - linux-ppc64le
  - linux

node_js:
 - "6"

install:
 - npm install

before_script:
 - npm install grunt-cli -g

script:
 - grunt test

branches:
  only:
    - master
